parse:
  additional_commands:
    catkin_package:
      flags: []
      kwargs:
        CAKTIN_DEPENDS: '*'
        DEPENDS: '*'
        INCLUDE_DIRS: '*'
        LIBRARIES: '*'
    catkin_add_gtest:
      pargs: 1
    add_rostest_gtest:
      pargs: 2
format:
  disable: false
  line_width: 88
  tab_size: 2
  use_tabchars: false
  fractional_tab_policy: use-space
  max_subgroups_hwrap: 5
  max_pargs_hwrap: 10
  max_rows_cmdline: 2
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: true
  dangle_align: prefix
  min_prefix_chars: 4
  max_prefix_chars: 10
  max_lines_hwrap: 1
  line_ending: unix
  command_case: canonical
  keyword_case: unchanged
  always_wrap: [catkin_package, FetchContent_Declare]
  enable_sort: true
  autosort: false
  require_valid_layout: false
