---
# generic
z_offset_scale: 2.0
visualize: true
# node
marker_scale: 0.40
marker_alpha: 0.6
use_sphere_marker: false
use_label: false
label_height: 0.5
label_scale: 0.45
use_bounding_box: true
bounding_box_alpha: 0.9
bbox_wireframe_scale: 0.05
bbox_wireframe_edge_scale: 0.05
collapse_bounding_box: true
# edge
use_edge_source: true
interlayer_edge_scale: 0.05
interlayer_edge_alpha: 0.3
interlayer_edge_use_color: true
interlayer_edge_insertion_skip: 10
intralayer_edge_scale: 0.03
intralayer_edge_alpha: 0.6
intralayer_edge_use_color: false
intralayer_edge_insertion_skip: 0
