---
pgmo:
  time_horizon: 15.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  min_cluster_size: 40
  cluster_tolerance: 0.25
freespace_places:
  type: gvd
  gvd:
    max_distance_m: 4.5
    min_distance_m: 0.2
    min_diff_m: 0.1
    voronoi_config:
      mode: L1_THEN_ANGLE
      min_distance_m: 0.30
      parent_l1_separation: 20
      parent_cos_angle_separation: 0.2
  graph:
    type: CompressionGraphExtractor
    compression_distance_m: 1.0
    min_node_distance_m: 0.4
    min_edge_distance_m: 0.2
    node_merge_distance_m: 0.5
    add_heuristic_edges: true
    add_overlap_edges: false
    add_freespace_edges: true
    freespace_edges:
      num_nodes_to_check: 10
      num_neighbors_to_find: 2
      min_clearance_m: 0.2
  tsdf_interpolator:
    type: downsample
    ratio: 2
