---
frames:
  - child_frame_id: acl_jackal/os_sensor
    frame_id: acl_jackal/ouster_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/imu_link_ned
    frame_id: acl_jackal/imu_link
    qw: -3.0e-06
    qx: 0.707105
    qy: 0.707108
    qz: -3.0e-06
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/base_link
    frame_id: acl_jackal/base
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/chassis_link
    frame_id: acl_jackal/base_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/embedded_imu_link
    frame_id: acl_jackal/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_bottom_screw_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_camera_link
    frame_id: acl_jackal/forward_bottom_screw_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0175
    z: 0.0125
  - child_frame_id: acl_jackal/forward_color_frame
    frame_id: acl_jackal/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.015
    z: 0.0
  - child_frame_id: acl_jackal/forward_color_optical_frame
    frame_id: acl_jackal/forward_color_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_depth_frame
    frame_id: acl_jackal/forward_camera_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_depth_optical_frame
    frame_id: acl_jackal/forward_depth_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: 0.0
    z: 0.0
  # - child_frame_id: acl_jackal/forward_link
  #   frame_id: acl_jackal/sensor_plate_link
  #  # frame_id: acl_jackal/velodyne
  #   qw: 1.0
  #   qx: 0.0
  #   qy: 0.0
  #   qz: 0.0
  #   x: 0.0
  #   y: 0.0
  #   z: 0.16
  - child_frame_id: acl_jackal/forward_link
    frame_id: acl_jackal/velodyne_link
    qw: 0.9986270311879281
    qx: 0.01911147027517028
    qy: 0.0487295543528025
    qz: 0.0020578671685843133
    x: 0.0432082697117232
    # y: 0.3083065514449883
    y: 0.1
    z: -0.12883465090206989
  - child_frame_id: acl_jackal/forward_left_ir_frame
    frame_id: acl_jackal/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_left_ir_optical_frame
    frame_id: acl_jackal/forward_left_ir_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/forward_right_ir_frame
    frame_id: acl_jackal/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.05
    z: 0.0
  - child_frame_id: acl_jackal/forward_right_ir_optical_frame
    frame_id: acl_jackal/forward_right_ir_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/front_fender_link
    frame_id: acl_jackal/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/front_mount
    frame_id: acl_jackal/mid_mount
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.12
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/imu_link
    frame_id: acl_jackal/sensor_plate_link
    qw: 0.714862
    qx: 0.006431
    qy: -0.002871
    qz: 0.69923
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/mid_mount
    frame_id: acl_jackal/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.184
  - child_frame_id: acl_jackal/navsat_link
    frame_id: acl_jackal/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.18
    y: 0.126
    z: 0.1815
  - child_frame_id: acl_jackal/rear_fender_link
    frame_id: acl_jackal/chassis_link
    qw: -0.0
    qx: 0.0
    qy: 0.0
    qz: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/rear_mount
    frame_id: acl_jackal/mid_mount
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.12
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/sensor_plate_link
    frame_id: acl_jackal/base_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.13
    y: 0.0
    z: 0.19
  - child_frame_id: acl_jackal/velodyne_base_link
    frame_id: acl_jackal/velodyne_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: acl_jackal/velodyne
    frame_id: acl_jackal/velodyne_base_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0377
  - child_frame_id: acl_jackal/velodyne_link
    frame_id: acl_jackal/sensor_plate_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.33
  - child_frame_id: acl_jackal/forward_depth_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: acl_jackal/forward_color_frame
    frame_id: acl_jackal/forward_link
    qw: 0.999999
    qx: -0.000818
    qy: 0.000897
    qz: 0.000793
    x: -0.000189
    y: -0.058908
    z: 3.4e-05
  - child_frame_id: acl_jackal/forward_infra1_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: acl_jackal/forward_infra1_optical_frame
    frame_id: acl_jackal/forward_infra1_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: acl_jackal/forward_infra2_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.094853
    z: -0.0
  - child_frame_id: acl_jackal/forward_infra2_optical_frame
    frame_id: acl_jackal/forward_infra2_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: acl_jackal/forward_gyro_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.01602
    y: -0.03022
    z: 0.0074
  - child_frame_id: acl_jackal/forward_imu_optical_frame
    frame_id: acl_jackal/forward_gyro_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: acl_jackal/forward_accel_frame
    frame_id: acl_jackal/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.01602
    y: -0.03022
    z: 0.0074
  - child_frame_id: acl_jackal/forward_accel_optical_frame
    frame_id: acl_jackal/forward_accel_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
