---
frames:
  - child_frame_id: apis/imu_link_ned
    frame_id: apis/imu_link
    qw: -3.0e-06
    qx: 0.707105
    qy: 0.707108
    qz: -3.0e-06
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/base_link
    frame_id: apis/base
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/chassis_link
    frame_id: apis/base_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/embedded_imu_link
    frame_id: apis/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_bottom_screw_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_camera_link
    frame_id: apis/forward_bottom_screw_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0175
    z: 0.0125
  - child_frame_id: apis/forward_color_frame
    frame_id: apis/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.015
    z: 0.0
  - child_frame_id: apis/forward_color_optical_frame
    frame_id: apis/forward_color_frame
    qw: -0.5
    qx: 0.5
    qy: -0.5
    qz: 0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_depth_frame
    frame_id: apis/forward_camera_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_depth_optical_frame
    frame_id: apis/forward_depth_frame
    qw: -0.5
    qx: 0.5
    qy: -0.5
    qz: 0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_link
    frame_id: apis/sensor_plate_link
    qw: 0.999671
    qx: -0.011861
    qy: 0.022502
    qz: -0.003268
    x: 0.248356
    y: 0.036366
    z: 0.297964
  - child_frame_id: apis/forward_left_ir_frame
    frame_id: apis/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_left_ir_optical_frame
    frame_id: apis/forward_left_ir_frame
    qw: -0.5
    qx: 0.5
    qy: -0.5
    qz: 0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/forward_right_ir_frame
    frame_id: apis/forward_depth_frame
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.05
    z: 0.0
  - child_frame_id: apis/forward_right_ir_optical_frame
    frame_id: apis/forward_right_ir_frame
    qw: -0.5
    qx: 0.5
    qy: -0.5
    qz: 0.5
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/front_fender_link
    frame_id: apis/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/front_mount
    frame_id: apis/mid_mount
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.12
    y: 0.0
    z: 0.0
  - child_frame_id: apis/imu_link
    frame_id: apis/sensor_plate_link
    qw: 0.688817
    qx: 0.001027
    qy: -0.00098
    qz: 0.724934
    x: 0.0
    y: 0.0
    z: 0.3
  - child_frame_id: apis/mid_mount
    frame_id: apis/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.184
  - child_frame_id: apis/navsat_link
    frame_id: apis/chassis_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.18
    y: 0.126
    z: 0.1815
  - child_frame_id: apis/ouster_link
    frame_id: apis/sensor_plate_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.12
    y: 0.0
    z: 0.315
  - child_frame_id: apis/rear_fender_link
    frame_id: apis/chassis_link
    qw: 0.0
    qx: 0.0
    qy: 0.0
    qz: 1.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/rear_mount
    frame_id: apis/mid_mount
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.12
    y: 0.0
    z: 0.0
  - child_frame_id: apis/sensor_plate_link
    frame_id: apis/base_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/ublox_link
    frame_id: apis/sensor_plate_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: 0.0
    z: 0.0
  - child_frame_id: apis/os_imu
    frame_id: apis/ouster_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.006253
    y: -0.011775
    z: 0.007645
  - child_frame_id: apis/os_lidar
    frame_id: apis/ouster_link
    qw: 0.0
    qx: 0.0
    qy: 0.0
    qz: 1.0
    x: 0.0
    y: 0.0
    z: 0.03618
  - child_frame_id: apis/forward_depth_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_color_frame
    frame_id: apis/forward_link
    qw: 0.999994
    qx: 0.002214
    qy: -0.000294
    qz: 0.002485
    x: -0.000295
    y: -0.05903
    z: 0.000123
  - child_frame_id: apis/forward_color_optical_frame
    frame_id: apis/forward_aligned_depth_to_color_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_aligned_depth_to_color_frame
    frame_id: apis/forward_link
    qw: 0.999994
    qx: 0.002214
    qy: -0.000294
    qz: 0.002485
    x: -0.000295
    y: -0.05903
    z: 0.000123
  - child_frame_id: apis/forward_infra1_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_infra1_optical_frame
    frame_id: apis/forward_infra1_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_infra2_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: 0.0
    y: -0.094947
    z: -0.0
  - child_frame_id: apis/forward_infra2_optical_frame
    frame_id: apis/forward_infra2_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_gyro_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.01602
    y: -0.03022
    z: 0.0074
  - child_frame_id: apis/camera_imu_optical_frame
    frame_id: apis/forward_gyro_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
  - child_frame_id: apis/forward_accel_frame
    frame_id: apis/forward_link
    qw: 1.0
    qx: 0.0
    qy: 0.0
    qz: 0.0
    x: -0.01602
    y: -0.03022
    z: 0.0074
  - child_frame_id: apis/forward_accel_optical_frame
    frame_id: apis/forward_accel_frame
    qw: 0.5
    qx: -0.5
    qy: 0.5
    qz: -0.5
    x: 0.0
    y: -0.0
    z: -0.0
