lcd_visualizer_ns: "/dsg/lcd_visualizer"
lcd_agent_horizon_s: 3.5
descriptor_creation_horizon_m: 17.0
lcd:
    enable_agent_registration: true
    object_radius_m: 15.0
    num_semantic_classes: 20
    place_radius_m: 15.0
    place_histogram_config:
        min: 0.5
        max: 2.5
        bins: 30
    registration_configs:
        objects:
            min_correspondences: 5
            min_inliers: 5
            log_registration_problem: false
            registration_output_path: ""
    search_configs:
        agent:
            min_time_separation_s: 150.0
            min_score: 0.039
            min_registration_score: 0.039  # this gets overriden
            max_registration_matches: 1
            min_score_ratio: 1.0
            min_match_separation_m: 0.0
            type: "L1"
        objects:
            min_time_separation_s: 150.0
            min_score: 0.3
            min_registration_score: 0.93
            max_registration_matches: 5
            min_score_ratio: 0.7
            min_match_separation_m: 5.0
            type: "L1"
        places:
            min_time_separation_s: 150.0
            min_score: 0.5
            min_registration_score: 1.5
            max_registration_matches: 5
            min_score_ratio: 0.7
            min_match_separation_m: 5.0
            type: "L1"
    teaser:
        estimate_scaling: false
        noise_bound: 0.10
        cbar2: 1.0
        rotation_gnc_factor: 1.4
        rotation_max_iterations: 100
        rotation_cost_threshold: 1.0e-6
        kcore_heuristic_threshold: 0.5
        inlier_selection_mode: "PMC_EXACT"
