---
pgmo:
  time_horizon: 100.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  min_cluster_size: 25
  cluster_tolerance: 0.18
freespace_places:
  type: gvd
  gvd:
    max_distance_m: 7.0
    min_distance_m: 0.2
    min_diff_m: 0.1
    voronoi_config:
      mode: L1_THEN_ANGLE
      min_distance_m: 0.30
      parent_l1_separation: 20
      parent_cos_angle_separation: 0.2
  graph:
    type: CompressionGraphExtractor
    compression_distance_m: 1.0
    min_node_distance_m: 0.4
    min_edge_distance_m: 0.3
    add_heuristic_edges: false
surface_places:
  prefix: P
  place_memory_radius_m: 30
  active_place_radius_m: 16.0
  mesh_active_window_m: 20.0
  cluster_tolerance: 1
  min_cluster_size: 100
  max_cluster_size: 100000
  min_final_place_size: 7
  min_final_place_points: 10
