---
pgmo:
  time_horizon: 15.0
  d_graph_resolution: 2.5
  mesh_resolution: 0.005
objects:
  min_cluster_size: 40
  cluster_tolerance: 0.25
freespace_places:
  type: gvd
  gvd:
    max_distance_m: 5.0
    min_distance_m: 0.5
    min_diff_m: 0.1
    voronoi_config:
      mode: L1_THEN_ANGLE
      min_distance_m: 0.30
      parent_l1_separation: 20
      parent_cos_angle_separation: 0.2
  graph:
    type: CompressionGraphExtractor
    compression_distance_m: 3.0
    min_node_distance_m: 0.6
    min_edge_distance_m: 0.3
    node_merge_distance_m: 1.5
    add_heuristic_edges: false
