---
color_topic: /tesse/left_cam/rgb/image_raw
depth_topic: /tesse/depth_cam/mono/image_raw
start: -1.0
duration: 30.0
intrinsics: [415.69219, 415.69219, 360.0, 240.0]
# gvd integration and graph extraction
max_distance_m: 10.0
min_distance_m: 0.2
min_diff_m: 0.0
min_weight: 1.0e-6
positive_distance_only: true
min_basis_for_extraction: 2
num_buckets: 20
multi_queue: false
extract_graph: true
voronoi_config:
  mode: L1_THEN_ANGLE
  min_distance_m: 0.40
  parent_l1_separation: 12
  parent_cos_angle_separation: 0.0
graph_extractor:
  min_extra_basis: 2
  min_vertex_basis: 4
  merge_new_nodes: true
  node_merge_distance_m: 0.3
  edge_splitting_merge_nodes: true
  max_edge_split_iterations: 5
  max_edge_deviation: 4
  add_freespace_edges: true
  freespace_active_neighborhood_hops: 1
  freespace_edge_num_neighbors: 3
  freespace_edge_min_clearance_m: 0.2
  add_component_connection_edges: true
  connected_component_window: 10
  connected_component_hops: 2
  component_nodes_to_check: 50
  component_nearest_neighbors: 1
  component_max_edge_length_m: 5.0
  component_min_clearance_m: 0.5
  remove_isolated_nodes: true
  use_color: true
integrator_threads: 12
voxel_carving_enabled: true
use_const_weight: false
default_truncation_distance: 0.3
max_weight: 10000
min_ray_length_m: 0.1
max_ray_length_m: 10.0
allow_clear: true
use_weight_dropoff: true
use_sparsity_compensation_factor: false
integration_order_mode: mixed
enable_anti_grazing: false
start_voxel_subsampling_factor: 2
max_consecutive_ray_collisions: 2
clear_checks_every_n_frames: 1
