---
type: FrontendModule
pgmo:
  horizon: 15.0
  track_mesh_graph_mapping: true
  full_compression_method: 2  # voxel clearing
  graph_compression_method: 1  # voxblox
  d_graph_resolution: 2.5
  output_mesh_resolution: 0.005
objects:
  prefix: O
  active_horizon_s: 10.0
  active_index_horizon_m: 7.0
  min_cluster_size: 40
  max_cluster_size: 100000
  cluster_tolerance: 0.25
min_object_vertices: 40
prune_mesh_indices: true
enable_active_mesh_pub: false
enable_segmented_mesh_pub: false
places:
  type: gvd
  filter_places: true
  min_places_component_size: 3
  gvd:
    max_distance_m: 4.5
    min_distance_m: 0.2
    min_diff_m: 0.1
    min_weight: 1.0e-6
    positive_distance_only: true
    min_basis_for_extraction: 1
    num_buckets: 20
    multi_queue: false
    extract_graph: true
    voronoi_config:
      mode: L1_THEN_ANGLE
      min_distance_m: 0.30
      parent_l1_separation: 20
      parent_cos_angle_separation: 0.2
  graph:
    type: CompressionGraphExtractor
    compression_distance_m: 1.5
    validate_graph: false
    min_node_distance_m: 0.4
    min_edge_distance_m: 0.25
    node_merge_distance_m: 0.7
    # heurisitic edges
    add_heuristic_edges: false
    add_overlap_edges: true
    overlap_edges:
      num_neighbors_to_check: 4
      min_clearance_m: 0.4
    add_freespace_edges: false
    merge_policy: distance
