---
lcd_agent_horizon_s: 3.5
descriptor_creation_horizon_m: 15.0
detector:
  graph_configs:
    - layer: objects
      descriptors:
        type: ObjectGraphDescriptor
        subgraph: {fixed_radius: true, max_radius_m: 13.0}
      matching:
        min_time_separation_s: 25.0
        min_score: 0.3
        min_registration_score: 0.90
        max_registration_matches: 2
        min_score_ratio: 0.9
        min_match_separation_m: 5.0
        type: L1
      registration:
        type: GraphTeaserSolver
        min_correspondences: 5
        min_inliers: 5
        teaser:
          estimate_scaling: false
          noise_bound: 0.100
          rotation_gnc_factor: 1.4
          rotation_max_iterations: 100
          rotation_cost_threshold: 1.0e-6
          kcore_heuristic_threshold: 0.5
          inlier_selection_mode: PMC_EXACT
          max_clique_time_limit: 3600
    - layer: places
      descriptors:
        type: PlaceGraphDescriptor
        subgraph: {fixed_radius: true, max_radius_m: 13.0}
        histogram_config: {min: 0.5, max: 2.5, bins: 30}
      matching:
        min_time_separation_s: 25.0
        min_score: 0.2
        min_registration_score: 1.5
        max_registration_matches: 5
        min_score_ratio: 0.7
        min_match_separation_m: 5.0
        type: L1
