---
# general
z_offset_scale: 3.4
visualize: false
# nodes
marker_scale: 0.6
marker_alpha: 0.8
use_sphere_marker: false
use_label: true
label_height: 1.0
label_scale: 0.75
use_bounding_box: false
bounding_box_alpha: 0.5
collapse_bounding_box: false
# edges
use_edge_source: true
interlayer_edge_scale: 0.08
interlayer_edge_alpha: 0.4
interlayer_edge_use_color: true
interlayer_edge_insertion_skip: 1
intralayer_edge_scale: 0.1
intralayer_edge_alpha: 0.8
intralayer_edge_use_color: false
intralayer_edge_insertion_skip: 0
