---
pgmo:
  horizon: 100.0
  track_mesh_graph_mapping: true
  full_compression_method: 2    # voxel clearing
  graph_compression_method: 1    # voxblox
  d_graph_resolution: 2.5
  output_mesh_resolution: 0.02
objects:
  prefix: O
  active_horizon_s: 10.0
  active_index_horizon_m: 7.0    # TODO(nathan) check
  min_cluster_size: 25
  max_cluster_size: 100000
  cluster_tolerance: 0.25
min_object_vertices: 20
prune_mesh_indices: true
enable_active_mesh_pub: false
enable_segmented_mesh_pub: false
