---
map:
  voxels_per_side: 16
  voxel_size: 0.2
  truncation_distance: 0.3
map_window:
  type: spatial
  max_radius_m: 10.0
reconstruction:
  mesh:
    min_weight: 0.0001
    integrator_threads: -1
  tsdf:
    verbosity: 1
    num_threads: -1
    interpolation_method: bilinear
    semantic_integrator:
      type: MLESemanticIntegrator
