---
paths: [khronos, khronos_ros]
map_window: {type: temporal, window_sec: 5.0}
active_window:
  type: ActiveWindow
  verbosity: 0
  sensor_map_mode: Strict
  sensors:
    rgbd:
      object_detector: {type: InstanceForwarding, min_cluster_size: 30, max_range: 7.0, min_range: 0.05, verbosity: 0, instance_filter: {type: CategoryFilter}}
      tracker:
        type: MaxIouTracker
        track_by: voxels
        min_semantic_iou: 0.1
        min_cross_iou: 0.3
        voxel_size: 0.2
        min_num_observations: 10
      projective_integrator: {semantic_integrator: {type: SingleLabelIntegrator, labels_to_ignore: []}}
    velodyne16:
      object_detector: {type: InstanceForwarding, min_cluster_size: 10, max_range: 15.0, min_range: 0.05, verbosity: 0, instance_filter: {type: CategoryFilter}}
      tracker:
        type: MaxIouTracker
        track_by: voxels
        min_semantic_iou: 0.1
        min_cross_iou: 0.3
        voxel_size: 0.2
        min_num_observations: 5
      projective_integrator:
        use_constant_weight: true
        extra_integration_distance: 3.0
        extra_integration_distance_labels: [1]
        semantic_integrator: {type: SingleLabelIntegrator, labels_to_ignore: []}
  object_extractor:
    type: MeshObjectExtractor
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.005
    max_object_volume: 100.0
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.0
    min_object_reconstruction_observations: 10
    visualize_classification: false
    object_reconstruction_resolution: -0.02
    projective_integrator:
      sensor_map_mode: Strict
      sensors:
        rgbd: {}
        velodyne16: {use_constant_weight: true}
  khronos_sinks:
    - type: ActiveWindowVisualizer
      sensor_displays:
        sensor_map_mode: Strict
        sensors:
          rgbd: {}
          velodyne16: {height_scale: 32.0}
frontend: {enable_mesh_objects: false}
