---
active_window:
  type: ReconstructionModule
  tsdf: {semantic_integrator: {type: MLESemanticIntegrator}}
frontend:
  enable_mesh_objects: true
  objects: {bounding_box_type: AABB, min_cluster_size: 40, cluster_tolerance: 0.25}
