---
paths: [khronos]
active_window:
  type: ActiveWindow
  projective_integrator: {semantic_integrator: {type: MLESemanticIntegrator}}
  object_detector: {type: ConnectedSemantics, min_cluster_size: 50, grid_size: 0.1, max_range: 4.5}
  tracker: {type: MaxIouTracker, track_by: voxels, min_semantic_iou: 0.25, min_cross_iou: 0.1, voxel_size: 0.2, temporal_window: 10.0, min_num_observations: 15}
  object_extractor:
    type: MeshObjectExtractor
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.005  # m^3
    max_object_volume: 10.0  # m^3
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.5
    min_object_reconstruction_observations: 10
    object_reconstruction_resolution: -0.02  # Positive: voxel size in meters.
    projective_integrator: {num_threads: 8}
frontend:
  enable_mesh_objects: false
